# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure Neko path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0700
    owner: "{{ neko_uid }}"
    group: "{{ neko_gid }}"
  with_items:
    - {path: "{{ neko_base_path }}", when: true}

- name: Ensure Neko traefik labels are installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ neko_base_path }}/labels"
    owner: "{{ neko_uid }}"
    group: "{{ neko_gid }}"
    mode: 0640

- name: Ensure Neko configuration is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/env.j2"
    dest: "{{ neko_base_path }}/env"
    owner: "{{ neko_uid }}"
    group: "{{ neko_gid }}"
    mode: 0640

- name: Ensure Neko container image is pulled
  community.docker.docker_image:
    name: "{{ neko_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ neko_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else neko_container_image_force_pull }}"

- name: Ensure Neko container network is created
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ neko_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure neko.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/neko.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ neko_identifier }}.service"
    mode: 0644
