---

- name: Ensure neko network is created in Docker
  community.docker.docker_network:
    name: "{{ neko_container_network }}"
    driver: bridge

- name: Ensure neko path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0700
    owner: "{{ neko_uid }}"
    group: "{{ neko_gid }}"
  with_items:
    - {path: "{{ neko_base_path }}", when: true}

- name: Ensure neko traefik labels are installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ neko_base_path }}/labels"
    owner: "{{ neko_uid }}"
    group: "{{ neko_gid }}"
    mode: 0640

- name: Ensure neko configuration is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/env.j2"
    dest: "{{ neko_base_path }}/env"
    owner: "{{ neko_uid }}"
    group: "{{ neko_gid }}"
    mode: 0640

- name: Ensure neko container image is pulled
  community.docker.docker_image:
    name: "{{ neko_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure neko.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/neko.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ neko_identifier }}.service"
    mode: 0644
