# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Neko installation tasks
  when: neko_enabled | bool
  tags:
    - setup-all
    - setup-neko
    - install-all
    - install-neko
  block:
    - name: Validate Neko configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Neko
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Neko uninstallation tasks
  when: not neko_enabled | bool
  tags:
    - setup-all
    - setup-neko
  block:
    - name: Uninstall Neko
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
