# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: neko_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
  tags:
    - setup-all
    - setup-neko
    - install-all
    - install-neko

- block:
    - when: neko_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-neko
    - install-all
    - install-neko

- block:
    - when: not neko_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-neko
