---

- name: Fail if required neko settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - neko_hostname
    - neko_password
    - neko_password_admin

