# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "neko_environment_variables_extension", "new": "neko_environment_variables_additional_variables" }
    - { "old": "neko_screen", "new": "neko_environment_variables_neko_desktop_screen" }
    - { "old": "neko_password", "new": "neko_environment_variables_neko_member_multiuser_user_password" }
    - { "old": "neko_password_admin", "new": "neko_environment_variables_neko_member_multiuser_admin_password" }
    - { "old": "neko_epr", "new": "neko_environment_variables_neko_webrtc_epr" }
    - { "old": "neko_icelite", "new": "neko_environment_variables_neko_webrtc_icelite" }
    - { "old": "neko_ipfetch", "new": "neko_environment_variables_neko_webrtc_ip_retrieval_url" }
    - { "old": "neko_http_header_content_permission_policy", "new": "neko_http_header_permissions_policy" }

- name: Fail if required Neko settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - neko_uid
    - neko_gid
    - neko_hostname
    - neko_path_prefix
    - neko_container_network

- name: Fail if Neko member provider is invalid
  ansible.builtin.fail:
    msg: >-
      neko_environment_variables_neko_member_provider must be 'multiuser', 'file', 'object', or 'noauth'
  when: "neko_environment_variables_neko_member_provider not in ['multiuser', 'file', 'object', 'noauth']"

- name: Run if Traefik is enabled
  when: neko_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Neko are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - neko_container_labels_traefik_hostname
        - neko_container_labels_traefik_path_prefix

    - name: Fail if neko_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          neko_container_labels_traefik_path_prefix (`{{ neko_container_labels_traefik_path_prefix }}`) must be `/`.
          Neko does not support hosting under a subpath yet.
      when: "neko_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `neko_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if neko_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          neko_container_labels_traefik_path_prefix (`{{ neko_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/neko`).
      when: "neko_container_labels_traefik_path_prefix != '/' and neko_container_labels_traefik_path_prefix[-1] == '/'"
