---
- name: Ensure neko user registered - {{ user.username | quote }}
  ansible.builtin.command:
    cmd: |-
      {{ devture_systemd_docker_base_host_command_docker }} exec {{ neko_identifier }}
      /neko/neko admin account create
      --username {{ user.username | quote }}
      --email {{ user.initial_email | quote }}
      --password {{ user.initial_password | quote }}
  register: neko_create_account_result
  changed_when: neko_create_account_result.rc == 0 and 'is already in use' not in neko_create_account_result.stderr
  failed_when: neko_create_account_result.rc > 0 and 'is already in use' not in neko_create_account_result.stderr

- name: Ensure neko user is promoted - {{ user.username | quote }}
  ansible.builtin.command:
    cmd: |-
      {{ devture_systemd_docker_base_host_command_docker }} exec {{ neko_identifier }}
      /neko/neko admin account promote
      --username {{ user.username | quote }}
  when: user.initial_type == 'admin'
